/**
 * Types for the Lyrics + Chords feature in weblooper.
 *
 * Design goals:
 * - Support AI-generated timed lyrics (from vocals stem)
 * - Support timed chords (from guitar/bass/piano stems)
 * - Allow user corrections and manual editing
 * - Persist alongside stem sessions (local + Drive sync)
 * - Keep it simple for v1 while leaving room for word-level timing later
 */

export interface TimedChord {
  /** Start time in seconds (original 1.0x speed) */
  time: number
  /** Chord symbol (e.g. "C", "G#m7", "Fmaj7/E") */
  chord: string
  /** Optional duration in seconds */
  duration?: number
  /** Confidence from the chord model (0-1), if available */
  confidence?: number
}

export interface LyricSegment {
  id: string

  /** Start time in seconds (original 1.0x speed, logical time) */
  start: number
  /** End time in seconds (optional but recommended for highlighting) */
  end?: number

  /** The text to display for this segment (usually one line or phrase) */
  text: string

  /** Optional chords that occur during this segment */
  chords?: TimedChord[]

  /** Optional section label (Verse, Chorus, Bridge, etc.) */
  section?: string

  /** Where this segment came from / how reliable it is */
  source: 'ai' | 'user' | 'mixed'

  /** Model info if generated by AI */
  model?: string

  /** User confidence / quality rating (0-1), if they edited it */
  confidence?: number
}

export interface LyricTrack {
  id: string

  /** Which stem session this track belongs to */
  stemSessionId: string

  /** Original duration of the full track (for percentage calculations) */
  duration: number

  /** The actual timed content */
  segments: LyricSegment[]

  /** Metadata about how this track was created */
  metadata: {
    generatedAt: number
    lyricsModel?: string
    chordsModel?: string
    vocalsStemUsed: boolean
    processingTimeMs?: number
    /** Which quantized / model variant was used */
    modelVariant?: string
  }

  /** When the user last edited this track */
  lastEditedAt?: number

  version: 1
}

/**
 * Lightweight summary used in lists and the stem session meta.
 */
export interface LyricTrackSummary {
  id: string
  stemSessionId: string
  segmentCount: number
  generatedAt: number
  lyricsModel?: string
  lastEditedAt?: number
}